###########################
# Configuration for rubocop
# in .rubocop.yml

inherit_from:
  - .rubocop_todo.yml

##############
# Project specific overrides here, example:
# Metrics/BlockLength:
#   Exclude:
#    - 'tasks/the_huge_task.rake'
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
   - 'test/**/*'
Naming/UncommunicativeMethodParamName:
  Enabled: false

