sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.0
- 2.3.3
- 2.4.1
- 2.5.1
before_install: gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
env:
  global:
    - CC_TEST_REPORTER_ID=8db13b5426f53feb5dc03024a07bf4440018c3bcf0f857fa80c68f4d05c224d7
script:
- bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: rubygems
  api_key:
    secure: TKNqMYZRxQn5AcXqB05mo1LtcDF8GNYVXtjsApgFi4XX7gx18CwnUuoqRLROcO+PuEkeSvgbdP2yK8FOvcDK+TJtX+5rm3TgQG7zUMB2scSSRcxp+t6lOYb7hPZJBr/uFqwbt/mZp4/dMEiDCgBuHGacXL55pWDo9Re1f0CgoXpJ2tfhDVs+m+ZOji9PgcjMQFjEJynqWJnSqDGbpmNKlISV8O2vx88PyoK8a3j/EKSdO+/aKjP2FLj7iWKUR5+9tEQJiRbWkwJxrJ3gn7Iw1K0lX/vAw6zhaXHMRIPQu/a/XtBwS/Rx00wooF0SSqSkaks2nOggd9O/VnknwmYdaebpgKsJvWh9YYhJNjUw03dVp9Hr0FVfBGhtj+Z4OW97WuBVfAPrOlbZVUsSXpbYNGuZyNeJEt3PeWWIqJlDSoGCWY8juMsC/loAFNw2a8ps1I4O2ooGtfk0I24gOkNiNhgL9GdRlsJSwC6NR8c59p+PlRN84ynU9Nh58l8L/gJ28cvB8gCObZ455ZlavV0BiJWrjyupBWvcBM6SkL7AYHNMKWV4X72FCxbBG/BI6dLSCeJnsws3PxpOuqSSrr74dmHvz9zEuTCs3NNHuL3wK7p8jS/MONxJf21EDFgeIuIIEe3ovxgu+ih6GbJo0EPw3mxOPQXotIyziw+A0pF852k=
  gem: 'yes'
  on:
    repo: tcob/ROPRQUEST